project_id = "wpokxylpyleghcfdxgjd"

[functions.extract-attendance]
verify_jwt = false

[functions.analyze-competencies]
verify_jwt = false

[functions.extract-combined-data]
verify_jwt = false

[functions.forward-plumber-webhook]
verify_jwt = false
